### ISSUE TITLE
Problem running vHLLE with SMASH IC at LHC energies

### ISSUE THREAD

**Issue by akschaefer** [yukarpenko/vhlle#7]
We ran into a problem running the SMASH+vHLLE hybrid at LHC energies. See https://github.com/smash-transport/smash-vhlle-hybrid/issues/1. 
@thegarzo already figured the reason is that 'the number of particles is Hardcoded to be NP=10000 in icPartSmash.h'.
While this can easily be fixed, by increasing this hard-coded number, the question would still be how to deal with it on the long run. Because increasing this number to a very large results in an increased memory consumption. Alternatively, I could also imagine introducing a config parameter that may then be updated by the user. Are there any opinions, @yukarpenko ?

**Comment by yukarpenko** [comment]
I am wondering why not to use std::vector here? In principle, the plain C array with hardcoded size was a quick solution, but instead one can create vectors instead with capacity 10000 and push_back() to them. Once the capacity is reached, the vector will resize automatically - the resize isn't fast, but I am probably talking about milliseconds here.

**Comment by akschaefer** [comment]
Thanks for the impact, @yukarpenko. I created a pull request according to your suggestions.
